project:
  type: book
  output-dir: docs

book:
  title: "Cool Quarto Course"
  author: "Padma"
  chapters:
    - index.qmd
    - introduction.qmd
    - foundations.qmd
    - workflows.qmd
    - wrap-up.qmd

format:
  html:
    theme: cosmo
    toc: true